#!/usr/bin/env bash
# installs a fire wall

sudo apt-get -y install ufw
sudo sed -i "s/IPV6=no/IPV6=yes/" /etc/default/ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming

# configuration
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https

# start
sudo ufw enable
